[package]
name = "gqlforge-typedefs-common"
version = "0.1.0"
edition = "2024"
description = "Common type definitions for gqlforge"
license = "Apache-2.0"

[dependencies]
async-graphql = { workspace = true }
schemars = { version = "1.0.0" }
serde_json = { workspace = true }
